services:
  - type: web
    name: dexter-chat
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        value: your-key-here
      - key: SLACK_BOT_TOKEN
        value: your-bot-token
      - key: SLACK_SIGNING_SECRET
        value: your-signing-secret
    plan: free
